#!/bin/sh
# Build a pinned, Python-free SDK. Caller provides verified source and PROJ.
set -eu
src=${1:?GDAL source directory}
build=${2:?Build directory}
cmake -S "$src" -B "$build" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCMAKE_PREFIX_PATH=/usr/local -DBUILD_TESTING=OFF -DBUILD_APPS=OFF \
    -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JAVA_BINDINGS=OFF -DBUILD_CSHARP_BINDINGS=OFF \
    -DGDAL_USE_EXTERNAL_LIBS=OFF -DGDAL_USE_INTERNAL_LIBS=ON \
    -DGDAL_USE_GEOS=ON -DGDAL_USE_SQLITE3=ON \
    -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF -DOGR_BUILD_OPTIONAL_DRIVERS=OFF \
    -DGDAL_ENABLE_DRIVER_GTIFF=ON -DGDAL_ENABLE_DRIVER_PNG=ON -DGDAL_ENABLE_DRIVER_AAIGRID=ON \
    -DOGR_ENABLE_DRIVER_SQLITE=ON -DOGR_ENABLE_DRIVER_GPKG=ON \
    -DOGR_ENABLE_DRIVER_GEOJSON=ON -DOGR_ENABLE_DRIVER_SHAPE=ON
cmake --build "$build" -j"${GDAL_BUILD_JOBS:-4}"
cmake --install "$build"
