//! Isolated concrete capacity/serialization prototype, not a source classifier or production codec.
//! Immutable fixture roles stand in for future independently reviewed physical-view classification.
use serde::{Deserialize,Deserializer,Serialize,Serializer,de::{self,DeserializeSeed,MapAccess,SeqAccess,Visitor},ser::{SerializeMap,SerializeSeq}};
use serde_json::value::RawValue;
use std::{alloc::{GlobalAlloc,Layout,System},borrow::Cow,cell::Cell,fmt,io::{self,Write},mem::size_of,sync::atomic::{AtomicBool,AtomicUsize,Ordering::SeqCst}};
#[derive(Clone,Copy,Debug)] pub(crate) struct JsonLimits {pub bytes:usize,pub depth:u64,pub value_nodes:usize}
#[derive(Debug)] pub(crate) enum FormatError {InvalidInput(String),Unsupported(String),ResourceLimit(String)}
#[path="/tmp/rusty-tiles-next-vector-compression-audit/codec/p2-proof-preparation-20261010/inputs/source/src/content_integrity/json.rs"] mod json;

// Bounded nonallocating trace storage is instrumentation, not a production owner or RSS claim.
#[derive(Clone,Copy)]struct Event{kind:u8,old:usize,new:usize,live:usize}
const ZERO_EVENT:Event=Event{kind:0,old:0,new:0,live:0};const TRACE_SLOTS:usize=32768;
static mut EVENTS:[Event;TRACE_SLOTS]=[ZERO_EVENT;TRACE_SLOTS];
static LIVE:AtomicUsize=AtomicUsize::new(0);static PEAK:AtomicUsize=AtomicUsize::new(0);
static TRACE:AtomicBool=AtomicBool::new(false);static EVENT_COUNT:AtomicUsize=AtomicUsize::new(0);
fn event(kind:u8,old:usize,new:usize){if TRACE.load(SeqCst){let n=EVENT_COUNT.fetch_add(1,SeqCst);if n<TRACE_SLOTS{unsafe{std::ptr::addr_of_mut!(EVENTS).cast::<Event>().add(n).write(Event{kind,old,new,live:LIVE.load(SeqCst)});}}}}
struct Meter;unsafe impl GlobalAlloc for Meter{
 unsafe fn alloc(&self,l:Layout)->*mut u8{event(1,0,l.size());PEAK.fetch_max(LIVE.load(SeqCst)+l.size(),SeqCst);let p=System.alloc(l);if !p.is_null(){LIVE.fetch_add(l.size(),SeqCst);}p}
 unsafe fn alloc_zeroed(&self,l:Layout)->*mut u8{event(2,0,l.size());PEAK.fetch_max(LIVE.load(SeqCst)+l.size(),SeqCst);let p=System.alloc_zeroed(l);if !p.is_null(){LIVE.fetch_add(l.size(),SeqCst);}p}
 unsafe fn dealloc(&self,p:*mut u8,l:Layout){event(3,l.size(),0);System.dealloc(p,l);LIVE.fetch_sub(l.size(),SeqCst);}
 unsafe fn realloc(&self,p:*mut u8,l:Layout,n:usize)->*mut u8{event(4,l.size(),n);PEAK.fetch_max(LIVE.load(SeqCst)+n,SeqCst);let q=System.realloc(p,l,n);if !q.is_null(){LIVE.fetch_add(n,SeqCst);LIVE.fetch_sub(l.size(),SeqCst);}q}
}
#[global_allocator]static ALLOCATOR:Meter=Meter;
fn start()->usize{TRACE.store(false,SeqCst);EVENT_COUNT.store(0,SeqCst);let b=LIVE.load(SeqCst);PEAK.store(b,SeqCst);TRACE.store(true,SeqCst);b}
fn report(stage:&str,baseline:usize){let captured=TRACE.swap(false,SeqCst);let count=EVENT_COUNT.load(SeqCst);let peak=PEAK.load(SeqCst);let live=LIVE.load(SeqCst);println!("{{\"stage\":\"{stage}\",\"baselineRequested\":{baseline},\"peakRequestedOldPlusNew\":{peak},\"liveRequested\":{live},\"events\":{count},\"detailedTraceCaptured\":{captured},\"traceComplete\":{}}}",count<=TRACE_SLOTS);assert!(count<=TRACE_SLOTS,"bounded trace overflow is not complete evidence");for n in 0..count{let e=unsafe{std::ptr::addr_of!(EVENTS).cast::<Event>().add(n).read()};println!("{{\"allocationStage\":\"{stage}\",\"event\":{n},\"kind\":{},\"oldBytes\":{},\"newBytes\":{},\"liveBefore\":{}}}",e.kind,e.old,e.new,e.live);}}

#[derive(Clone,Copy,Debug,PartialEq)]enum PrepError{ResourceLimit,InvalidShape,Unsupported,DuplicateDeclaration}
#[derive(Clone,Copy,PartialEq)]enum Fault{None,Arena,Views,Refs,OwnedKey,Edits,Candidate}
#[derive(Clone,Copy,Debug)]struct Span{start:usize,len:usize}
struct RawField<'a>{key:Cow<'a,str>,value:&'a RawValue}
struct Arena<'a>{fields:Vec<RawField<'a>>,limit:usize}
#[derive(Clone,Copy,Debug)]struct SourceRange{offset:usize,len:usize}
#[derive(Clone,Copy,Debug)]enum StrideAgreement{NoDense,Agreed(usize),Conflicting}
#[derive(Clone,Copy,Debug)]struct Consumers{stride:StrideAgreement,raw_roles:u8}
#[derive(Clone,Copy,Debug)]enum Action{Raw,Encode{stride:usize,count:usize,bound:usize},ValidateIdentity{source:SourceRange,stride:usize,count:usize}}
struct PreparedView{fields:Span,source:SourceRange,consumers:Consumers,action:Action}
#[derive(Clone,Copy)]enum ViewEdit{Raw{offset:usize},Encoded{offset:usize,len:usize,fallback_offset:usize}}
#[derive(Clone,Copy,PartialEq)]#[repr(u8)]enum KnownExtension{Features,Metadata,Polygon,Restart,Quantization,Unlit,Meshopt}
fn known(name:&str)->Result<KnownExtension,PrepError>{Ok(match name{"EXT_mesh_features"=>KnownExtension::Features,"EXT_structural_metadata"=>KnownExtension::Metadata,"EXT_mesh_polygon"=>KnownExtension::Polygon,"KHR_mesh_primitive_restart"=>KnownExtension::Restart,"KHR_mesh_quantization"=>KnownExtension::Quantization,"KHR_materials_unlit"=>KnownExtension::Unlit,"EXT_meshopt_compression"=>KnownExtension::Meshopt,_=>return Err(PrepError::Unsupported)})}
// Actual retained declarations borrow the caller's raw lexical spelling, not decoded Strings.
#[derive(Clone,Copy)]struct DeclRef<'a>{raw:&'a RawValue,kind:KnownExtension}
struct Declarations<'a>{used:[Option<DeclRef<'a>>;7],required:[Option<DeclRef<'a>>;7],used_len:usize,required_len:usize}
#[derive(Clone,Copy,Default)]struct Facts{source_bytes:usize,output_bytes:usize,views:usize,raw_views:usize,new_views:usize,existing_views:usize,accessors:usize,logical_bytes:usize}
struct RepackPlan<'a>{source:&'a[u8],arena:Arena<'a>,root:Span,buffer:Span,views:Vec<PreparedView>,declarations:Declarations<'a>,facts:Facts,metadata:bool,plan_estimate:usize,virtual_fallback_len:usize}
enum Plan<'a>{Identity{source:&'a[u8],facts:Facts},Repack(RepackPlan<'a>)}
struct Encoded{bytes:Vec<u8>,facts:Facts}
#[derive(Deserialize)]#[serde(rename_all="camelCase")]struct FixtureEdit{bin_bytes:u64,fallback_bytes:u64,byte_offset:u64,byte_length:u64,byte_stride:u64,count:u64,metadata:bool}
fn checked_bytes<T>(n:usize)->Result<usize,PrepError>{n.checked_mul(size_of::<T>()).filter(|n|*n<=isize::MAX as usize).ok_or(PrepError::ResourceLimit)}
fn exact<T>(n:usize,site:Fault,fault:Fault)->Result<Vec<T>,PrepError>{checked_bytes::<T>(n)?;if n>0&&fault==site{return Err(PrepError::ResourceLimit);}let mut v=Vec::new();v.try_reserve_exact(n).map_err(|_|PrepError::ResourceLimit)?;assert_eq!(v.capacity(),n,"root must inspect actual std capacity, never transfer an unverified capacity coefficient");Ok(v)}
fn add(a:usize,b:usize)->Result<usize,PrepError>{a.checked_add(b).ok_or(PrepError::ResourceLimit)}
fn plan_work(j:usize,k:usize,v_upper:usize)->Result<usize,PrepError>{let payload=j.checked_mul(3).ok_or(PrepError::ResourceLimit)?;let arena=checked_bytes::<RawField<'_>>(k)?;let views=checked_bytes::<PreparedView>(v_upper)?;let refs=checked_bytes::<&RawValue>(v_upper.max(1))?;add(add(add(add(payload,8)?,arena)?,views)?,refs)}

struct Key<'c>{failure:&'c Cell<Option<PrepError>>,fault:Fault}
impl<'de>DeserializeSeed<'de>for Key<'_>{type Value=Cow<'de,str>;fn deserialize<D:Deserializer<'de>>(self,d:D)->Result<Self::Value,D::Error>{d.deserialize_str(self)}}
impl<'de>Visitor<'de>for Key<'_>{type Value=Cow<'de,str>;fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("field name")}
 fn visit_borrowed_str<E:de::Error>(self,s:&'de str)->Result<Self::Value,E>{Ok(Cow::Borrowed(s))}
 fn visit_str<E:de::Error>(self,s:&str)->Result<Self::Value,E>{if self.fault==Fault::OwnedKey||checked_bytes::<u8>(s.len()).is_err(){self.failure.set(Some(PrepError::ResourceLimit));return Err(E::custom("owned key capacity"));}let mut key=String::new();if key.try_reserve_exact(s.len()).is_err(){self.failure.set(Some(PrepError::ResourceLimit));return Err(E::custom("owned key reserve"));}let capacity=key.capacity();key.push_str(s);assert_eq!(key.capacity(),capacity);assert_eq!(capacity,s.len());Ok(Cow::Owned(key))}}
struct Fields<'p,'a>{arena:&'p mut Arena<'a>,failure:&'p Cell<Option<PrepError>>,fault:Fault}
impl<'de>DeserializeSeed<'de>for Fields<'_,'de>{type Value=Span;fn deserialize<D:Deserializer<'de>>(self,d:D)->Result<Span,D::Error>{d.deserialize_map(self)}}
impl<'de>Visitor<'de>for Fields<'_,'de>{type Value=Span;fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("targeted object")}
 fn visit_map<M:MapAccess<'de>>(self,mut m:M)->Result<Span,M::Error>{let start=self.arena.fields.len();while let Some(key)=m.next_key_seed(Key{failure:self.failure,fault:self.fault})?{if self.arena.fields.len()>=self.arena.limit{self.failure.set(Some(PrepError::ResourceLimit));return Err(de::Error::custom("arena slots exhausted"));}let value=m.next_value::<&RawValue>()?;self.arena.fields.push(RawField{key,value});}Ok(Span{start,len:self.arena.fields.len()-start})}}
fn object<'a>(raw:&'a RawValue,arena:&mut Arena<'a>,fault:Fault)->Result<Span,PrepError>{let failure=Cell::new(None);let mut d=serde_json::Deserializer::from_str(raw.get());d.disable_recursion_limit();let result=Fields{arena,failure:&failure,fault}.deserialize(&mut d).map_err(|_|failure.get().unwrap_or(PrepError::InvalidShape))?;d.end().map_err(|_|PrepError::InvalidShape)?;Ok(result)}
fn value<'a>(arena:&Arena<'a>,span:Span,key:&str)->Option<&'a RawValue>{arena.fields[span.start..span.start+span.len].iter().find(|f|f.key==key).map(|f|f.value)}
struct ArrayCount;impl<'de>Visitor<'de>for ArrayCount{type Value=usize;fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("array")}
 fn visit_seq<M:SeqAccess<'de>>(self,mut m:M)->Result<usize,M::Error>{let mut n=0usize;while m.next_element::<&RawValue>()?.is_some(){n=n.checked_add(1).ok_or_else(||de::Error::custom("array count overflow"))?;}Ok(n)}}
fn array_count(raw:&RawValue)->Result<usize,PrepError>{let mut d=serde_json::Deserializer::from_str(raw.get());d.deserialize_seq(ArrayCount).map_err(|_|PrepError::InvalidShape)}
struct Refs<'p,'a>(&'p mut Vec<&'a RawValue>);impl<'de>Visitor<'de>for Refs<'_,'de>{type Value=();fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("array")}
 fn visit_seq<M:SeqAccess<'de>>(self,mut m:M)->Result<(),M::Error>{while let Some(raw)=m.next_element::<&RawValue>()?{if self.0.len()==self.0.capacity(){return Err(de::Error::custom("secured ref slots exhausted"));}self.0.push(raw);}Ok(())}}
fn array_refs<'a>(raw:&'a RawValue,n:usize,fault:Fault)->Result<Vec<&'a RawValue>,PrepError>{let mut refs=exact(n,Fault::Refs,fault)?;{let mut d=serde_json::Deserializer::from_str(raw.get());d.deserialize_seq(Refs(&mut refs)).map_err(|_|PrepError::InvalidShape)?;}assert_eq!(refs.len(),n);Ok(refs)}
struct DeclRaws<'p,'a>{out:&'p mut[Option<&'a RawValue>;7],n:&'p mut usize}
impl<'de>Visitor<'de>for DeclRaws<'_,'de>{type Value=();fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("extension declaration array")}
 fn visit_seq<M:SeqAccess<'de>>(self,mut m:M)->Result<(),M::Error>{while let Some(raw)=m.next_element::<&RawValue>()?{if *self.n==7{return Err(de::Error::custom("more than finite known declarations"));}self.out[*self.n]=Some(raw);*self.n+=1;}Ok(())}}
struct ExtensionName;impl<'de>Visitor<'de>for ExtensionName{type Value=Result<KnownExtension,PrepError>;fn expecting(&self,f:&mut fmt::Formatter)->fmt::Result{f.write_str("known extension name")}
 fn visit_borrowed_str<E:de::Error>(self,s:&'de str)->Result<Self::Value,E>{Ok(known(s))}fn visit_str<E:de::Error>(self,s:&str)->Result<Self::Value,E>{Ok(known(s))}}
fn declarations<'a>(raw:Option<&'a RawValue>)->Result<([Option<DeclRef<'a>>;7],usize),PrepError>{let mut refs=[None;7];let mut n=0;if let Some(raw)=raw{{let mut d=serde_json::Deserializer::from_str(raw.get());d.deserialize_seq(DeclRaws{out:&mut refs,n:&mut n}).map_err(|_|PrepError::Unsupported)?;}}let mut out=[None;7];let mut seen=0u8;for i in 0..n{let raw=refs[i].unwrap();let kind={let mut d=serde_json::Deserializer::from_str(raw.get());d.deserialize_str(ExtensionName).map_err(|_|PrepError::InvalidShape)??};let flag=1u8<<(kind as u8);if seen&flag!=0{return Err(PrepError::DuplicateDeclaration);}seen|=flag;out[i]=Some(DeclRef{raw,kind});}Ok((out,n))}
fn prepare<'a>(input:&'a[u8],checked:&json::CheckedDocument<'a>,edit:&FixtureEdit,work_limit:usize,view_limit:usize,fault:Fault,selected:Action)->Result<RepackPlan<'a>,PrepError>{
 let k=checked.value_nodes();let v_upper=k.min(view_limit);let estimate=plan_work(input.len(),k,v_upper)?;if estimate>work_limit{return Err(PrepError::ResourceLimit);} // Accepted JSON precedes this Plan-only no-allocation gate.
 let mut arena=Arena{fields:exact(k,Fault::Arena,fault)?,limit:k};let root=object(checked.raw(),&mut arena,fault)?;
 let(used,used_len)=declarations(value(&arena,root,"extensionsUsed"))?;let(required,required_len)=declarations(value(&arena,root,"extensionsRequired"))?;
 let buffers=value(&arena,root,"buffers").ok_or(PrepError::InvalidShape)?;if array_count(buffers)?!=1{return Err(PrepError::Unsupported);}let buffer_refs=array_refs(buffers,1,fault)?;let buffer_raw=buffer_refs[0];drop(buffer_refs);let buffer=object(buffer_raw,&mut arena,fault)?;
 let view_raw=value(&arena,root,"bufferViews").ok_or(PrepError::InvalidShape)?;let v=array_count(view_raw)?;if v>view_limit{return Err(PrepError::ResourceLimit);}let refs=array_refs(view_raw,v,fault)?;let mut views=exact(v,Fault::Views,fault)?;
 for raw in &refs{let fields=object(raw,&mut arena,fault)?;views.push(PreparedView{fields,source:SourceRange{offset:0,len:usize::try_from(edit.fallback_bytes).map_err(|_|PrepError::ResourceLimit)?},consumers:Consumers{stride:StrideAgreement::Agreed(usize::try_from(edit.byte_stride).map_err(|_|PrepError::ResourceLimit)?),raw_roles:0},action:selected});}
 drop(refs);let accessors=value(&arena,root,"accessors").map(array_count).transpose()?.unwrap_or(0);let(raw_views,new_views,existing_views)=match selected{Action::Raw=>(v,0,0),Action::Encode{..}=>(0,v,0),Action::ValidateIdentity{..}=>(0,0,v)};let facts=Facts{source_bytes:input.len(),views:v,raw_views,new_views,existing_views,accessors,logical_bytes:v.checked_mul(usize::try_from(edit.fallback_bytes).map_err(|_|PrepError::ResourceLimit)?).ok_or(PrepError::ResourceLimit)?,..Facts::default()};assert_eq!(arena.fields.capacity(),k);assert_eq!(views.capacity(),v);
 Ok(RepackPlan{source:input,arena,root,buffer,views,declarations:Declarations{used,required,used_len,required_len},facts,metadata:edit.metadata,plan_estimate:estimate,virtual_fallback_len:usize::try_from(edit.fallback_bytes).map_err(|_|PrepError::ResourceLimit)?})
}

// The fixed serializer consumes concrete action/edit fields; fixture selection is not semantic classification.
struct Buffer<'p,'a>{p:&'p RepackPlan<'a>,bin_len:usize}impl Serialize for Buffer<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(None)?;for f in &self.p.arena.fields[self.p.buffer.start..self.p.buffer.start+self.p.buffer.len]{if f.key=="byteLength"{m.serialize_entry(f.key.as_ref(),&self.bin_len)?}else{m.serialize_entry(f.key.as_ref(),f.value)?}}m.end()}}
struct FallbackFlag;impl Serialize for FallbackFlag{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(Some(1))?;m.serialize_entry("fallback",&true)?;m.end()}}
struct FallbackExtension;impl Serialize for FallbackExtension{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(Some(1))?;m.serialize_entry("EXT_meshopt_compression",&FallbackFlag)?;m.end()}}
struct Fallback(usize);impl Serialize for Fallback{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(Some(2))?;m.serialize_entry("byteLength",&self.0)?;m.serialize_entry("extensions",&FallbackExtension)?;m.end()}}
struct Buffers<'p,'a>{p:&'p RepackPlan<'a>,bin_len:usize}impl Serialize for Buffers<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut q=s.serialize_seq(Some(2))?;q.serialize_element(&Buffer{p:self.p,bin_len:self.bin_len})?;q.serialize_element(&Fallback(self.p.virtual_fallback_len))?;q.end()}}
struct Extension{action:Action,edit:ViewEdit}impl Serialize for Extension{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let(stride,count)=match self.action{Action::Encode{stride,count,..}=>(stride,count),_=>return Err(serde::ser::Error::custom("fixed encode fixture action required"))};let(offset,len)=match self.edit{ViewEdit::Encoded{offset,len,..}=>(offset,len),_=>return Err(serde::ser::Error::custom("encoded edit required"))};let mut m=s.serialize_map(Some(7))?;m.serialize_entry("buffer",&0u8)?;m.serialize_entry("byteOffset",&offset)?;m.serialize_entry("byteLength",&len)?;m.serialize_entry("byteStride",&stride)?;m.serialize_entry("count",&count)?;m.serialize_entry("mode","ATTRIBUTES")?;m.serialize_entry("filter","NONE")?;m.end()}}
struct Extensions{action:Action,edit:ViewEdit}impl Serialize for Extensions{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(Some(1))?;m.serialize_entry("EXT_meshopt_compression",&Extension{action:self.action,edit:self.edit})?;m.end()}}
struct Views<'p,'a>{p:&'p RepackPlan<'a>,edits:&'p[ViewEdit]}impl Serialize for Views<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{struct V<'p,'a>{p:&'p RepackPlan<'a>,view:&'p PreparedView,edit:ViewEdit}impl Serialize for V<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(None)?;let fallback=match self.edit{ViewEdit::Encoded{fallback_offset,..}=>fallback_offset,ViewEdit::Raw{offset}=>offset};for f in &self.p.arena.fields[self.view.fields.start..self.view.fields.start+self.view.fields.len]{match f.key.as_ref(){"buffer"=>m.serialize_entry(f.key.as_ref(),&1u8)?,"byteOffset"=>m.serialize_entry(f.key.as_ref(),&fallback)?,_=>m.serialize_entry(f.key.as_ref(),f.value)?}}m.serialize_entry("extensions",&Extensions{action:self.view.action,edit:self.edit})?;m.end()}}let mut q=s.serialize_seq(Some(self.p.views.len()))?;for(view,edit)in self.p.views.iter().zip(self.edits){q.serialize_element(&V{p:self.p,view,edit:*edit})?;}q.end()}}
struct Names<'p,'a>{entries:&'p[Option<DeclRef<'a>>]}impl Serialize for Names<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut q=s.serialize_seq(None)?;let mut found=false;for e in self.entries{let e=e.unwrap();found|=e.kind==KnownExtension::Meshopt;q.serialize_element(e.raw)?;}if !found{q.serialize_element("EXT_meshopt_compression")?;}q.end()}}
struct Root<'p,'a>{p:&'p RepackPlan<'a>,bin_len:usize,edits:&'p[ViewEdit]}impl Serialize for Root<'_,'_>{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{let mut m=s.serialize_map(None)?;let d=&self.p.declarations;let used=Names{entries:&d.used[..d.used_len]};let required=Names{entries:&d.required[..d.required_len]};for f in &self.p.arena.fields[self.p.root.start..self.p.root.start+self.p.root.len]{match f.key.as_ref(){"buffers"=>m.serialize_entry(f.key.as_ref(),&Buffers{p:self.p,bin_len:self.bin_len})?,"bufferViews"=>m.serialize_entry(f.key.as_ref(),&Views{p:self.p,edits:self.edits})?,"extensionsUsed"=>m.serialize_entry(f.key.as_ref(),&used)?,"extensionsRequired"=>m.serialize_entry(f.key.as_ref(),&required)?,_=>m.serialize_entry(f.key.as_ref(),f.value)?}}if value(&self.p.arena,self.p.root,"extensionsUsed").is_none(){m.serialize_entry("extensionsUsed",&used)?;}if value(&self.p.arena,self.p.root,"extensionsRequired").is_none(){m.serialize_entry("extensionsRequired",&required)?;}m.end()}}
struct Count{n:usize,limit:usize}impl Write for Count{fn write(&mut self,b:&[u8])->io::Result<usize>{self.n=self.n.checked_add(b.len()).filter(|n|*n<=self.limit).ok_or_else(||io::Error::other("count limit"))?;Ok(b.len())}fn flush(&mut self)->io::Result<()>{Ok(())}}
struct Fixed<'p>{bytes:&'p mut Vec<u8>,limit:usize}impl Write for Fixed<'_>{fn write(&mut self,b:&[u8])->io::Result<usize>{let end=self.bytes.len().checked_add(b.len()).filter(|n|*n<=self.limit&&*n<=self.bytes.capacity()).ok_or_else(||io::Error::other("fixed sink"))?;self.bytes.extend_from_slice(b);assert_eq!(end,self.bytes.len());Ok(b.len())}fn flush(&mut self)->io::Result<()>{Ok(())}}
fn align(n:usize,a:usize)->usize{n.checked_add(a-1).unwrap()/a*a}
fn owned_bytes(p:&RepackPlan)->usize{p.arena.fields.iter().map(|f|match &f.key{Cow::Owned(s)=>s.capacity(),Cow::Borrowed(_)=>0}).sum()}
fn main(){
 if std::env::args().nth(1).as_deref()==Some("--checked-capacity-controls"){assert_eq!(checked_bytes::<RawField>(usize::MAX),Err(PrepError::ResourceLimit));assert_eq!(checked_bytes::<u8>(isize::MAX as usize),Ok(isize::MAX as usize));assert_eq!(checked_bytes::<u8>(isize::MAX as usize+1),Err(PrepError::ResourceLimit));assert_eq!(plan_work(usize::MAX,1,1),Err(PrepError::ResourceLimit));println!("{{\"checkedCapacityControls\":4,\"typedResourceLimit\":true,\"sourceAllocationsOrNativeInvocations\":0}}");return;}
 let args:Vec<String>=std::env::args().collect();let path=std::path::PathBuf::from(&args[1]);let work_limit=args.get(2).map(|s|s.parse().unwrap()).unwrap_or(usize::MAX);let fault=match args.get(3).map(String::as_str).unwrap_or("none"){"none"=>Fault::None,"arena"=>Fault::Arena,"views"=>Fault::Views,"refs"=>Fault::Refs,"owned_key"=>Fault::OwnedKey,"edits"=>Fault::Edits,"candidate"=>Fault::Candidate,_=>panic!("unknown fixture seam")};let role=args.get(4).map(String::as_str).unwrap_or("encode");
 let input=std::fs::read(path.join("input.json")).unwrap();let expected=std::fs::read(path.join("expected.glb")).unwrap();let binary=std::fs::read(path.join("binary.bin")).unwrap();let edit:FixtureEdit=serde_json::from_slice(&std::fs::read(path.join("edits.json")).unwrap()).unwrap();
 println!("{{\"typeSizes\":{{\"RawField\":{},\"PreparedView\":{},\"ViewEdit\":{},\"RawRef\":{},\"Span\":{},\"Declarations\":{},\"Facts\":{},\"RepackPlan\":{},\"Plan\":{},\"Encoded\":{}}},\"sourceCapacity\":{},\"oracleCapacityExcluded\":{},\"fixtureBinaryCapacityExcluded\":{},\"traceStaticBytesExcluded\":{}}}",size_of::<RawField>(),size_of::<PreparedView>(),size_of::<ViewEdit>(),size_of::<&RawValue>(),size_of::<Span>(),size_of::<Declarations>(),size_of::<Facts>(),size_of::<RepackPlan>(),size_of::<Plan>(),size_of::<Encoded>(),input.capacity(),expected.capacity(),binary.capacity(),size_of::<[Event;TRACE_SLOTS]>());
 let node_limit=args.get(5).map(|s|s.parse().unwrap()).unwrap_or(65536);let b=start();TRACE.store(false,SeqCst);let admitted=json::admit(&input,JsonLimits{bytes:1048576,depth:64,value_nodes:node_limit});report("accepted_pinned_json_admission_no_detailed_trace",b);let checked=match admitted{Ok(c)=>c,Err(e)=>{let kind=match e{FormatError::ResourceLimit(_)=>"ResourceLimit",FormatError::InvalidInput(_)=>"InvalidInput",FormatError::Unsupported(_)=>"Unsupported"};println!("{{\"jsonAdmissionOutcome\":\"{kind}\",\"noPlanAttempted\":true}}");return;}};if role=="admission"{println!("{{\"jsonAdmissionOutcome\":\"Accepted\",\"K\":{},\"nodeLimit\":{node_limit},\"noPlanAttempted\":true}}",checked.value_nodes());return;}
 let selected=match role{"encode"=>Action::Encode{stride:usize::try_from(edit.byte_stride).unwrap(),count:usize::try_from(edit.count).unwrap(),bound:usize::try_from(edit.byte_length).unwrap()},"raw"=>Action::Raw,"identity"=>Action::ValidateIdentity{source:SourceRange{offset:0,len:usize::try_from(edit.byte_length).unwrap()},stride:usize::try_from(edit.byte_stride).unwrap(),count:usize::try_from(edit.count).unwrap()},_=>panic!("unknown fixture-supplied role")};
 let b=start();let result=prepare(&input,&checked,&edit,work_limit,4096,fault,selected);report("concrete_plan_prepare",b);let plan=match result{Ok(p)=>p,Err(e)=>{println!("{{\"prepareOutcome\":\"{e:?}\",\"noPlanReturned\":true}}");return;}};
 let owned=owned_bytes(&plan);let borrowed=plan.arena.fields.iter().filter(|f|matches!(&f.key,Cow::Borrowed(_))).count();for f in &plan.arena.fields{if let Cow::Borrowed(s)=&f.key{let begin=input.as_ptr()as usize;let ptr=s.as_ptr()as usize;assert!(ptr>=begin&&ptr+s.len()<=begin+input.len());}}assert!(plan.arena.fields.len()<=checked.value_nodes());
 if path.join("shared_refs.json").exists(){let refs:Vec<usize>=serde_json::from_slice(&std::fs::read(path.join("shared_refs.json")).unwrap()).unwrap();for pair in refs.windows(2){assert!(std::ptr::eq(&plan.views[pair[0]],&plan.views[pair[1]]));}println!("{{\"sharedReferenceCount\":{},\"physicalDescriptors\":{},\"sameDescriptorIdentity\":true}}",refs.len(),plan.views.len());}
 println!("{{\"planCapacities\":{{\"arena\":{},\"arenaLen\":{},\"views\":{},\"ownedKeyBytes\":{},\"borrowedKeys\":{},\"K\":{},\"V\":{},\"planEstimateGate\":{},\"retainedRequested\":{}}}}}",plan.arena.fields.capacity(),plan.arena.fields.len(),plan.views.capacity(),owned,borrowed,checked.value_nodes(),plan.views.len(),plan.plan_estimate,plan.arena.fields.capacity()*size_of::<RawField>()+plan.views.capacity()*size_of::<PreparedView>()+owned);
 if role!="encode"{let facts=plan.facts;drop(plan);let identity_plan=Plan::Identity{source:&input,facts};let b=start();let mut identity=exact(input.len(),Fault::Candidate,fault).unwrap();identity.extend_from_slice(&input);assert_eq!(identity,input);assert!(!std::ptr::eq(identity.as_ptr(),input.as_ptr()));report("fixture_identity_role_plan_dropped_before_copy",b);drop(identity_plan);println!("{{\"fixtureSelectedRole\":\"{role}\",\"identityOracleMatch\":true,\"semanticClassifierOrNativeValidationProved\":false}}");return;}
 let b=start();let mut edits=match exact(plan.views.len(),Fault::Edits,fault){Ok(v)=>v,Err(e)=>{report("exact_edit_allocation",b);println!("{{\"encodePreparationOutcome\":\"{e:?}\"}}");return;}};for view in &plan.views{let len=match view.action{Action::Encode{bound,..}=>bound,_=>unreachable!()};edits.push(ViewEdit::Encoded{offset:usize::try_from(edit.byte_offset).unwrap(),len,fallback_offset:usize::try_from(edit.byte_offset).unwrap()});}report("exact_edit_allocation",b);
 assert_eq!(binary.len(),usize::try_from(edit.bin_bytes).unwrap());let root=Root{p:&plan,bin_len:binary.len(),edits:&edits};let bound=input.len().checked_add(512*plan.views.len()).unwrap()+1024;let b=start();let mut count=Count{n:0,limit:bound};serde_json::to_writer(&mut count,&root).unwrap();report("count_known_declarations_no_string_copy",b);let b=start();let mut too_small=Count{n:0,limit:count.n-1};assert!(serde_json::to_writer(&mut too_small,&root).is_err());report("count_one_below_negative",b);
 let j=if plan.metadata{align(20+count.n,8)-20}else{align(count.n,4)};let u=align(binary.len(),if plan.metadata{8}else{4});let total=28+j+u;let b=start();let mut bytes:Vec<u8>=match exact(total,Fault::Candidate,fault){Ok(v)=>v,Err(e)=>{report("direct_fixed_glb",b);println!("{{\"candidatePreparationOutcome\":\"{e:?}\"}}");return;}};bytes.resize(20,0);serde_json::to_writer(Fixed{bytes:&mut bytes,limit:20+count.n},&root).unwrap();bytes.resize(20+j,b' ');bytes.extend_from_slice(&(u as u32).to_le_bytes());bytes.extend_from_slice(b"BIN\0");bytes.extend_from_slice(&binary);bytes.resize(total,0);bytes[..4].copy_from_slice(b"glTF");bytes[4..8].copy_from_slice(&2u32.to_le_bytes());bytes[8..12].copy_from_slice(&(total as u32).to_le_bytes());bytes[12..16].copy_from_slice(&(j as u32).to_le_bytes());bytes[16..20].copy_from_slice(b"JSON");assert_eq!(bytes.capacity(),total);assert_eq!(bytes,expected,"independently frozen whole byte oracle");report("direct_fixed_glb",b);
 println!("{{\"exactJsonBytes\":{},\"candidateCapacity\":{},\"exactOracleMatch\":true,\"editsCapacity\":{}}}",count.n,bytes.capacity(),edits.capacity());
 drop(root);drop(bytes);drop(edits);drop(plan);drop(binary);drop(expected);let b=start();let mut identity=Vec::new();identity.try_reserve_exact(input.len()).unwrap();identity.extend_from_slice(&input);assert_eq!(identity,input);assert!(!std::ptr::eq(identity.as_ptr(),input.as_ptr()));report("plan_dropped_before_owned_identity_copy",b);
}
